Introducing Composed Task Runner App Starter
spring-cloud-task-app-starters/composed-task-runner pull request #2
Opened 2017-03-15 19:05 UTC by cppwfs

To build:
    mvn clean install -PgenerateApps
    cd apps/composedtaskrunner-task
    mvn clean install

    README.adoc has usage information.

    Resolves #20

2017-03-17 17:12 UTC, mminella requested changes

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +instance to launch the associated task definition.  For each task definition that is executed the
Long term we should add stories to support service binding and load balancing here (Eureka/Ribbon I'd assume).

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +Composed Task Runner will poll the database to verify that the task completed.
Another future optimization would be to allow the tasks to respond via the task messages.  Obviously it would be something that the task developer would need to do, but would be more efficient.  I realize this is out of scope for this, just saying the story should be added for the future.

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +If an ExitStatus 'FAILED' is returned in a sequence the Composed Task
What does this mean?  I know what it means, but since Spring Batch hasn't been mentioned in this doc yet, and Spring Cloud Task doesn't have an ExitStatus, the reader may not understand.  Also, what is considered success vs failure for each task execution?  Finally, `ExitStatus` should be formatted.

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +Will launch AAA and if AAA fails then BBB will be launched.  Else if AAA
Again, we need to define what failure and success means before this.  Also, we should demonstrate this via custom results as well.

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +ComposedTaskStepExecutionListener associated with it, such that once the step
Leave out this detail (mentioning the `ComposedTaskStepExecutionListener`).  It's an implementation detail and doesn't need to be exposed/discussed in the docs.

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +the StepExecutionListener will set the ExitStatus of that step based on the following rules:
Again leave out implementation details.

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +for the step will be FAILED.
Format `ExitStatus`.  Also, are we handling the population of the `ExitStatus` for the user or is that something they need to do.  I know we talked about it...

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +$$data-flow-uri$$:: $$The URI for the dataflow server that will receive task launch requests.$$ *($$URI$$, default: `$$<none>$$`)*
For a non-PCF environment, is this OK?  Meaning, on something like Kubernetes, is a single URL good enough to do we need to do something more robust like service binding (related to my earlier comment)?

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +$$interval-time-between-checks$$:: $$The amount of time in millis that the ComposedTaskStepExecutionListener
Remove the mentions of the implementation details.

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerJobBuilder.java
> +		Stack<Flow> executionStack = new Stack<>();
Minor nit pick, but you may want to consider a Deque since it's not synchronized.

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerJobBuilder.java
> +				new SimpleAsyncTaskExecutor())
We probably should allow the user to configure the number of threads for this app instead of using a `SimpleAsyncTaskExecutor`

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskRunnerConfiguration.java
> +	}
Why are these coming from this configuration and not a `TaskConfigurer`?

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskStepExecutionListenerTests.java
> +	ComposedTaskStepExecutionListener taskListener;
Is there a reason this isn't private?

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskStepExecutionListenerTests.java
> +		assertEquals(ExitStatus.UNKNOWN, this.taskListener.afterStep(this.stepExecution));
We need to verify that this use case works as we expect with batch.  Specifically that setting the `ExitStatus` to `UNKNOWN` will actually flip the `BatchStatus` on the step/job to `UNKNOWN`.  There are only very specific scenarios that `UNKNOWN` can be the result of a step (basically when a rollback of a transaction was not successful), so I'd want to be sure that the `BatchStatus` is being updated as we expect.

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/properties/ComposedTaskProperties.java
> +	private int maxWaitTime = 30000;
When we provide defaults, we want them to be logical defaults.  Meaning that the user shouldn't need to think about them until they need them.  If there isn't any logic to a default, we typically turn it off all together.  In this example, I'm assuming there is no analysis that says that 30 seconds is the logical default.  Because of that, I'd make the default to not have a max.

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/properties/ComposedTaskProperties.java
> +	private int intervalTimeBetweenChecks = 500;
Considering that each of these calls is verifying that a Spring Boot app ran, I'd loosen this up a bit.  I don't know many scenarios where we can get from the REST call to the launched app in a half a second.  I'd default it to something closer to once a minute for a default.

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskRunnerConfigurationTests.java
> +
All of these should be private, correct?

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/TaskLauncherTaskletTests.java
> +
Why are these not private?

2017-03-17 17:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/configuration/ComposedRunnerVisitorConfiguration.java
> +	ComposedRunnerJobBuilder getComposedJobBuilder(ComposedRunnerVisitor composedRunnerVisitor) {
Why package private?

2017-03-17 17:34 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +passed in via the `--graph` command line argument.
This was requested by Eric.

2017-03-17 18:44 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/TaskLauncherTaskletTests.java
> +
done

2017-03-17 18:44 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/configuration/ComposedRunnerVisitorConfiguration.java
> +	ComposedRunnerJobBuilder getComposedJobBuilder(ComposedRunnerVisitor composedRunnerVisitor) {
done

2017-03-17 18:46 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskRunnerConfigurationTests.java
> +
done

2017-03-17 19:00 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerVisitorTests.java
> +		}
Shouldn't they be closed if created?

2017-03-17 19:01 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/properties/ComposedTaskProperties.java
> +	private int intervalTimeBetweenChecks = 500;
done

2017-03-17 19:12 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerVisitorTests.java
> +		}
SCT closes them automatically if you don't tell it not to.  My question is why are you telling it not to?

2017-03-17 19:16 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerVisitorTests.java
> +		}
Some test cases throw an exception (planned) during the creation of the context.  And at teardown the applicationContext is null.

2017-03-17 19:17 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerVisitorTests.java
> +		}
Then that was what I was missing :)

2017-03-17 19:43 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/properties/ComposedTaskProperties.java
> +	private int maxWaitTime = 30000;
done

2017-03-17 20:22 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskStepExecutionListenerTests.java
> +		assertEquals(ExitStatus.UNKNOWN, this.taskListener.afterStep(this.stepExecution));
Should we choose a different status.  Like TIME_OUT?

2017-03-17 20:26 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskStepExecutionListenerTests.java
> +	ComposedTaskStepExecutionListener taskListener;
done

2017-03-17 20:33 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskRunnerStepFactory.java
> +				Isolation.READ_COMMITTED.value());
I thought this was across the board.   Or is it just for MYSQL?

2017-03-17 21:10 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskRunnerConfiguration.java
> +	}
done

2017-03-20 18:44 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerJobBuilder.java
> +				new SimpleAsyncTaskExecutor())
done

2017-03-20 19:12 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerJobBuilder.java
> +		Stack<Flow> executionStack = new Stack<>();
done

2017-03-20 19:14 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +$$interval-time-between-checks$$:: $$The amount of time in millis that the ComposedTaskStepExecutionListener
done

2017-03-20 19:19 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +for the step will be FAILED.
done

2017-03-20 19:22 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +the StepExecutionListener will set the ExitStatus of that step based on the following rules:
done

2017-03-20 19:22 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +ComposedTaskStepExecutionListener associated with it, such that once the step
done

2017-03-20 19:28 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +instance to launch the associated task definition.  For each task definition that is executed the
https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/3

2017-03-20 19:29 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +$$data-flow-uri$$:: $$The URI for the dataflow server that will receive task launch requests.$$ *($$URI$$, default: `$$<none>$$`)*
Created issue for this: https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/3

2017-03-21 20:23 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +If an ExitStatus 'FAILED' is returned in a sequence the Composed Task
moved contents around so that batch would be described before traversing the graph

2017-03-21 20:25 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +Will launch AAA and if AAA fails then BBB will be launched.  Else if AAA
moved contents around so that batch would be described before traversing the graph

2017-03-21 20:25 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +failure and DDD and EEE will not be launched.
done

2017-03-22 13:25 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskRunnerStepFactory.java
> +				Isolation.READ_COMMITTED.value());
or is this something that should be configurable by the user?

2017-03-22 14:23 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskStepExecutionListenerTests.java
> +		assertEquals(ExitStatus.UNKNOWN, this.taskListener.afterStep(this.stepExecution));
When the step status is set to UNKNOWN the overall Job Status is set to failed.  But is restartable.

2017-03-23 19:41 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +Composed Task Runner will poll the database to verify that the task completed.
Created issue for this: https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/4

2017-03-23 19:42 UTC, cppwfs commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskRunnerStepFactory.java
> +				Isolation.READ_COMMITTED.value());
After a discussion we agreed that making this configurable was not necessary.

2017-04-04 21:45 UTC, mminella requested changes
I don't see any tests around job status.  Making sure the job fails and is restartable when various errors occur.

2017-04-04 21:45 UTC, mminella commented on composedtaskrunner-task-app-dependencies/pom.xml
> +				</repository>
Why is the milestone repo included twice?

2017-04-04 21:45 UTC, mminella commented on composedtaskrunner-task-app-dependencies/pom.xml
> +			</pluginRepositories>
Why isn't the release repo included?

2017-04-04 21:45 UTC, mminella commented on pom.xml
> +				</pluginRepository>
Same comments as the previous POM

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +for the step will be FAILED.
Formatting in this paragraph

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/README.adoc
> +image::images/basictransitionwithsequence.png[basic transition with sequence]
I think the diagram for this is wrong.  It shouldn't be `Completed`, it should be `*`, shouldn't it?

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerJobBuilder.java
> + * Genererates a Composed Task Job Flow.
Elaborating on the javadoc would be nice

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerJobBuilder.java
> +
Odd blank row

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerJobBuilder.java
> +		}
This could be handled a bit more effeciently via a priming read (the if statement is only executed once):
```
if(!executionDeque.isEmpty()) {
    this.flowBuilder.start(exectuionDeque.pop());
}

while(!executionDeque.isEmpty()) {
    this.flowBuilder.next(executionDeque.pop());
}
```

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerJobBuilder.java
> +		}
Same priming read improvement can be done here as well.

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerJobBuilder.java
> +			}
Nit pick: `wildCardPresent = WILD_CARD.equals(transitionNode.getStatusToCheck());`  Prevents the extra if and prevents a potential NPE.

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerVisitor.java
> +	public Deque getFlowDeque() {
Why not just `getFlow()`?  The name ties you to that interface (instead of, say, a sub interface for example).

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskRunnerConfiguration.java
> +	}
Is this needed?  Shouldn't this occur automatically?

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskRunnerConfiguration.java
> +	}
Does this need to match in some way to the actually recorded task name?  If so, we should use the name directly instead of copying the logic from the `SimpleTaskNameResolver`.

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskRunnerStepFactory.java
> + * @author Michael Minella
I didn't do it ;)

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedTaskRunnerStepFactory.java
> +			Map<String, String> taskSpecificProps, List<String> arguments) {
I'm not a fan of putting non-required elements in the constructor args.  It forces the user to pass `null` instead of just not calling a setter.  Add to that, the fact that the only place this is used, the `arguments` value is hard coded to null (`StepBeanDefinitionRegistrar#registerBeanDefinitions`).

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/DataFlowConfiguration.java
> +		TaskOperations taskOperations = null;
This line is unnecessary.

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/DataFlowConfiguration.java
> +		return taskOperations;
Just `return dataFlowTemplate.taskOperations();`.

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/StepBeanDefinitionRegistrar.java
> +	 * @return all the apps referenced in the composed task.
The javadoc here could be beefed up to explain what the integer is...it's not obvious

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/TaskLauncherTasklet.java
> +				"composedTaskProperties must not be null");
Same comment about optional arguments in the constructor...

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/TaskLauncherTasklet.java
> +					.put("task-execution-id", executionId);
Odd formatting

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/TaskLauncherTasklet.java
> +public class TaskLauncherTasklet implements Tasklet {
I thought this was going to implement `StoppableTasklet`...

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/properties/ComposedTaskProperties.java
> +	private int maxWaitTime = 0;
Are we using the options to generate the javadoc for private members?  If not, these comments should be moved to the setters.

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/properties/ComposedTaskProperties.java
> +		}
Why is the throw required here since it's a hard coded URL?

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/properties/PropertyUtility.java
> +public class PropertyUtility {
Do these utilities not already exist?

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/support/TimeoutException.java
> +public class TimeoutException extends RuntimeException{
We probably should rename this to be more specific so it's not confused with the `java.concurrent.TimeoutException`

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/properties/PropertyUtilityTests.java
> +	public void retrieveWithQuotes() {
This test should have one property with a comma in the value.

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/properties/ComposedTaskPropertiesTests.java
> +		assertEquals(Integer.MAX_VALUE, properties.getSplitThreadQueueCapacity());
Can we make these defaults constants so that we don't have to update them in multiple places if we change them?

2017-04-04 21:45 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/test/java/org/springframework/cloud/task/app/composedtaskrunner/configuration/DataFlowTestConfiguration.java
> +	public static class TestTaskOperations implements TaskOperations {
Why aren't we just using a mock for this?

2017-04-05 15:34 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerJobBuilder.java
> +public class ComposedRunnerJobBuilder {
Why is this not a `FactoryBean` that encapsulates the parsing and generation?  The way this is configured in `ComposedTaskRunnerConfiguration` is odd...the `ComposedRunnerVisitor` and this "Builder" are beans.  It feels like the encapsulation of what's going on is wrong.  I'd expect you pass the DSL to a `FactoryBean` and out comes the job.  Instead it's really a collection of beans that all are tightly coupled to each other.

2017-04-05 16:10 UTC, mminella commented on spring-cloud-starter-task-composedtaskrunner/src/main/java/org/springframework/cloud/task/app/composedtaskrunner/ComposedRunnerVisitor.java
> +	private Deque flowDeque = new LinkedList();
Missing generics

2017-04-10 19:18 UTC, mminella commented
Resolved.

2017-04-10 19:18 UTC, closed without merging